name: Menke_repo
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pandas
  - matplotlib
  - scipy
  - jupyter
  - nbformat
  - pyppeteer
  - pip
  - pip:
    - nmrglue
    - notebook-as-pdf==0.4.0
